name: edashop
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck=1.4.2=py39hc99e966_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - console_shortcut=0.1.1=haa95532_6
  - et_xmlfile=2.0.0=py39haa95532_0
  - expat=2.7.3=h885b0b7_4
  - intel-openmp=2023.1.0=h59b6b97_46320
  - libblas=3.11.0=7_h6c93730_netlib
  - libcblas=3.11.0=7_hc41557d_netlib
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - liblapack=3.11.0=7_h018ca30_netlib
  - libzlib=1.3.1=h02ab6af_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - numpy=2.0.2=py39h60232e0_1
  - openpyxl=3.1.5=py39h827c3e9_1
  - openssl=3.0.19=hbb43b14_0
  - pandas=2.2.3=py39h2366fc2_3
  - pip=25.3=pyhc872135_0
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2025.2=py39haa95532_0
  - scipy=1.13.1=py39h1a10956_0
  - setuptools=80.9.0=py39haa95532_0
  - six=1.17.0=py39haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - certifi==2026.1.4
      - cffi==2.0.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - docopt==0.6.2
      - fonttools==4.60.2
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - packaging==25.0
      - pillow==11.3.0
      - pycparser==2.23
      - pyparsing==3.3.2
      - pyproj==3.6.1
      - rpy2==3.6.4
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
      - seaborn==0.13.2
      - shapely==2.0.7
      - stemgraphic==0.9.1
      - tzlocal==5.3.1
prefix: C:\Users\brdia\anaconda3\envs\edashop
